name: automerge

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  pull_request:
    branches:
      - main
      - develop
  workflow_run:
    workflows: ["lint"]
    types:
      - completed
  #check_suite:
  #  types:
  #    - completed
  #status: {}

jobs:
  log-github-actor:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
  automerge:
    needs: log-github-actor
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'FlamingTuri' }}
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          #MERGE_LABELS: "dependencies"
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: "rebase"
          MERGE_RETRY_SLEEP: "60000"
