name: automerge

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  pull_request:
    branches:
      - main
      - develop
  #workflow_run:
  #  workflows: ["lint"]
  #  types:
  #    - completed
  #check_suite:
  #  types:
  #    - completed
  #status: {}


jobs:
  log-github-actor:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
  wait-lint:
    needs: log-github-actor
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'FlamingTuri' }}
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'lint'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
  automerge:
    needs: wait-lint
    runs-on: ubuntu-latest
    steps:
      - uses: "DanySK/yaagha@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FORKS: "false"
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "merge"
          CLOSE_ON_CONFLICT: "false"
          DELETE_BRANCH_ON_CLOSE: "true"
          GIT_USER_NAME: "gventurini"
          GIT_USER_EMAIL: "giacomo.venturini3@gmail.com"
