name: lint
on: [push, pull_request]


jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          cd server
          python -m pip install -r requirements.dev.txt
          flake8 src
