name: release-artifacts

on:
  push:
    tags:
      - '*'

jobs:
  create-artifact:
    name: Create artifact for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            appName: main-linux
            artifactName: main-linux.tar.gz
          - os: windows-latest
            appName: main-windows.exe
            artifactName: main-windows.zip
          - os: macos-latest
            appName: main-macos.app
            artifactName: main-macos.zip
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: node .github/script/release-artifacts.mjs ${{ matrix.appName }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.appName }}
          path: server/dist/${{ matrix.appName }}
      - run: >
          node .github/script/zip-artifacts.mjs
          ${{ matrix.appName }}
          ${{ matrix.artifactName }}
      - uses: softprops/action-gh-release@v1
        with:
          files: server/dist/${{ matrix.artifactName }}
