name: release-artifacts

on:
  push:
    tags:
      - '*'

jobs:
  create-artifact:
    name: Create artifact for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            execName: main-linux
            artifactName: main-linux.tar.gz
          - os: windows-latest
            execName: main-windows.exe
            artifactName: main-windows.zip
          - os: macos-latest
            execName: main-macos.app
            artifactName: main-macos.zip
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: node .github/script/release-artifacts.mjs ${{ matrix.execName }} ${{ matrix.artifactName }}
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: ${{ matrix.artifactName }}
      #    path: server/dist/${{ matrix.artifactName }}

  release:
    needs: [create-artifact]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: dist
      - run: pwd
      - run: echo $HOME
      - run: mkdir `pwd`/release
      - run: ls -R
      - run: cp -R `pwd`/dist/* `pwd`/release
      - run: ls -laR
      - uses: softprops/action-gh-release@v1
        with:
          files: release/*
